- hosts: all
  tasks:
    - name: "create new deployment"
      command: kubectl apply -f /home/ubuntu/pod.yaml
    - name: "create new service"
      command: kubectl apply -f /home/ubuntu/service.yml