- hosts: _Master_node
  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/id_rsa"
  tasks:
    - name: "create new deployment"
      command: kubectl apply -f /home/ubuntu/pod.yml
    - name: "create new service"
      command: kubectl apply -f /home/ubuntu/service.yml
