kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
    template:
      metadata:
        labels:
          app: devops
        spec:
          containers:
            - name: devops
              image: sachindavra/dev-demo
              imagePullPolicy: Always
              ports:
                - containerPorts: 80